In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
sl_no             215 non-null int64
gender            215 non-null object
ssc_p             215 non-null float64
ssc_b             215 non-null object
hsc_p             215 non-null float64
hsc_b             215 non-null object
hsc_s             215 non-null object
degree_p          215 non-null float64
degree_t          215 non-null object
workex            215 non-null object
etest_p           215 non-null float64
specialisation    215 non-null object
mba_p             215 non-null float64
status            215 non-null object
salary            148 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [4]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [5]:
Quan=["ssc_p","hsc_p","degree_p","etest_p","mba_p","salary"]
Qual=["gender","ssc_b","hsc_b","degree_t","workex","specialisation","status",]

In [6]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

# Central Tendency

In [7]:
dataset["ssc_p"].mean()

67.30339534883721

In [8]:
dataset["ssc_p"].median()

67.0

In [9]:
dataset["ssc_p"].mode()[0]

62.0

In [10]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [11]:
descriptive=pd.DataFrame()

In [12]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=Quan)

In [13]:
descriptive

       ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN      NaN     NaN   NaN    NaN

In [14]:
descriptive["hsc_p"]["Median"]

nan

In [15]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=Quan)
for columnName in Quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]

In [16]:
descriptive

          ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean    67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median       67       65       66       71       62  265000
Mode         62       63       65       60     56.7  300000

In [17]:
import numpy as np
np.percentile(dataset["ssc_p"],10)

52.0

In [18]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=Quan)
for columnName in Quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
    descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]
    descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Min"]=dataset[columnName].min()
    descriptive[columnName]["Max"]=dataset.describe()[columnName]["max"]

In [19]:
descriptive

           ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median        67       65       66       71       62  265000
Mode          62       63       65       60     56.7  300000
Q1:25%      60.6     60.9       61       60   57.945  240000
Q2:50%        67       65       66       71       62  265000
Q3:75%      75.7       73       72     83.5   66.255  300000
99%           87    91.86    83.86       97  76.1142     NaN
Q4:100%     89.4     97.7       91       98    77.89  940000
IQR         15.1     12.1       11     23.5     8.31   60000
1.5rule    22.65    18.15     16.5    35.25   12.465   90000
Lesser     37.95    42.75     44.5    24.75    45.48  150000
Greater    98.35    91.15     88.5   118.75    78.72  390000
Min        40.89       37       50       50    51.21  200000
Max         89.4     97.7       91       98    77.89  940000

In [20]:
descriptive["hsc_p"]["Min"]<descriptive["hsc_p"]["Lesser"]

True

In [21]:
lesser=[]
greater=[]

for columnName in Quan:
    if(descriptive[columnName]["Min"]<descriptive[columnName]["Lesser"]):
        lesser.append(columnName)
    if(descriptive[columnName]["Max"]>descriptive[columnName]["Greater"]):
        greater.append(columnName)

In [22]:
lesser

['hsc_p']

In [23]:
greater

['hsc_p', 'degree_p', 'salary']

In [24]:
for columnName in lesser:
    dataset[columnName][dataset[columnName]<descriptive[columnName]["Lesser"]]=descriptive[columnName]["Lesser"]
for columnName in greater:
    dataset[columnName][dataset[columnName]>descriptive[columnName]["Greater"]]=descriptive[columnName]["Greater"]

C:\Users\FawadSaleem\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\FawadSaleem\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [25]:
lesser=[]
greater=[]

for columnName in Quan:
    if(descriptive[columnName]["Min"]<descriptive[columnName]["Lesser"]):
        lesser.append(columnName)
    if(descriptive[columnName]["Max"]>descriptive[columnName]["Greater"]):
        greater.append(columnName)
lesser
greater

['hsc_p', 'degree_p', 'salary']

In [26]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=Quan)
for columnName in Quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
    descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]
    descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Min"]=dataset[columnName].min()
    descriptive[columnName]["Max"]=dataset.describe()[columnName]["max"]

In [27]:
descriptive

           ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     67.3034  66.3347  66.3586  72.1006  62.2782  277649
Median        67       65       66       71       62  265000
Mode          62       63       65       60     56.7  300000
Q1:25%      60.6     60.9       61       60   57.945  240000
Q2:50%        67       65       66       71       62  265000
Q3:75%      75.7       73       72     83.5   66.255  300000
99%           87   91.129    83.86       97  76.1142     NaN
Q4:100%     89.4    91.15     88.5       98    77.89  390000
IQR         15.1     12.1       11     23.5     8.31   60000
1.5rule    22.65    18.15     16.5    35.25   12.465   90000
Lesser     37.95    42.75     44.5    24.75    45.48  150000
Greater    98.35    91.15     88.5   118.75    78.72  390000
Min        40.89    42.75       50       50    51.21  200000
Max         89.4    91.15     88.5       98    77.89  390000

In [28]:
dataset["ssc_p"].value_counts()

62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
80.60     1
65.20     1
80.40     1
59.96     1
78.50     1
Name: ssc_p, Length: 103, dtype: int64

In [29]:
freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","CumSum"])

In [30]:
freqTable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, CumSum]
Index: []

In [38]:
freqTable["Unique_Values"]=dataset["ssc_p"].value_counts().index
freqTable["Frequency"]=dataset["ssc_p"].value_counts().values
freqTable["Relative_Frequency"]=freqTable["Frequency"] / freqTable["Frequency"].sum()
freqTable["CumSum"]=freqTable["Relative_Frequency"].cumsum()

In [39]:
freqTable

     Unique_Values  Frequency  Relative_Frequency    CumSum
0            62.00         11            0.051163  0.051163
1            63.00         10            0.046512  0.097674
2            67.00          9            0.041860  0.139535
3            52.00          9            0.041860  0.181395
4            73.00          9            0.041860  0.223256
..             ...        ...                 ...       ...
98           80.60          1            0.004651  0.981395
99           65.20          1            0.004651  0.986047
100          80.40          1            0.004651  0.990698
101          59.96          1            0.004651  0.995349
102          78.50          1            0.004651  1.000000

[103 rows x 4 columns]

In [52]:
def freqTable(columnName,dataset):
    freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","CumSum"])
    freqTable["Unique_Values"]=dataset[columnName].value_counts().index
    freqTable["Frequency"]=dataset[columnName].value_counts().values
    freqTable["Relative_Frequency"]=freqTable["Frequency"] / freqTable["Frequency"].sum()
    freqTable["CumSum"]=freqTable["Relative_Frequency"].cumsum()
    return freqTable

In [53]:
freqTable("ssc_p",dataset)

     Unique_Values  Frequency  Relative_Frequency    CumSum
0            62.00         11            0.051163  0.051163
1            63.00         10            0.046512  0.097674
2            67.00          9            0.041860  0.139535
3            52.00          9            0.041860  0.181395
4            73.00          9            0.041860  0.223256
..             ...        ...                 ...       ...
98           80.60          1            0.004651  0.981395
99           65.20          1            0.004651  0.986047
100          80.40          1            0.004651  0.990698
101          59.96          1            0.004651  0.995349
102          78.50          1            0.004651  1.000000

[103 rows x 4 columns]

In [70]:
def Univariate(dataset,Quan):
    descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR",
                                    "1.5rule","Lesser","Greater","Min","Max","kurtosis","skew","Variance",
                                    "StandardD"],columns=Quan)
    for columnName in Quan:
        descriptive[columnName]["Mean"]=dataset[columnName].mean()
        descriptive[columnName]["Median"]=dataset[columnName].median()
        descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
        descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
        descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
        descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
        descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)
        descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]
        descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]
        descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"]
        descriptive[columnName]["Min"]=dataset[columnName].min()
        descriptive[columnName]["Max"]=dataset.describe()[columnName]["max"]
        descriptive[columnName]["kurtosis"]=dataset[columnName].kurtosis()
        descriptive[columnName]["skew"]=dataset[columnName].skew()
        descriptive[columnName]["Variance"]=dataset[columnName].var()
        descriptive[columnName]["StandardD"]=dataset[columnName].std()        
    return descriptive

In [71]:
Univariate(dataset,Quan)

              ssc_p      hsc_p   degree_p   etest_p     mba_p      salary
Mean        67.3034    66.3347    66.3586   72.1006   62.2782      277649
Median           67         65         66        71        62      265000
Mode             62         63         65        60      56.7      300000
Q1:25%         60.6       60.9         61        60    57.945      240000
Q2:50%           67         65         66        71        62      265000
Q3:75%         75.7         73         72      83.5    66.255      300000
99%              87     91.129      83.86        97   76.1142         NaN
Q4:100%        89.4      91.15       88.5        98     77.89      390000
IQR            15.1       12.1         11      23.5      8.31       60000
1.5rule       22.65      18.15       16.5     35.25    12.465       90000
Lesser        37.95      42.75       44.5     24.75     45.48      150000
Greater       98.35      91.15       88.5    118.75     78.72      390000
Min           40.89      42.75         50        50     51.21      200000
Max            89.4      91.15       88.5        98     77.89      390000
kurtosis   -0.60751  0.0869008 -0.0974897  -1.08858 -0.470723   -0.239837
skew      -0.132649   0.162611   0.204164  0.282308  0.313576      0.8067
Variance    117.228    112.064    53.6047   176.251   34.0284  2.9446e+09
StandardD   10.8272     10.586    7.32152    13.276   5.83338     54264.1

In [64]:
Kurtosis=dataset["ssc_p"].kurtosis()

In [65]:
Kurtosis

-0.6075102066986688

In [66]:
Skew=dataset["ssc_p"].skew()

In [67]:
Skew

-0.13264949031456927

In [68]:
Var=dataset["ssc_p"].var()
Var

117.2283767354923

In [69]:
Std=dataset["ssc_p"].std()
Std

10.827205398231452